### ISSUE TITLE
Aktualizacja opisu instalacji TF na Raspberry

### ISSUE THREAD

**Issue by krzysdz** [MetiumIoT/Metium#1]
Obecna [instrukcja](https://github.com/MetiumIoT/Metium/wiki/Instalacja-oprogramowania#instalacja) nie działa i istnieje oficjalna wersja TF dla architektury `armhf`.

**Wymagany jest python `>3.4` lub `2.7`.** Raspbian 9 ma 3.5.x (3.5.3 obecnie) i 2.7 (*domyślny*, 2.7.13), więc nie powinno to być problemem.<br>
Proponowany sposób instalacji ([opisany na stronie TensorFlow'a](https://www.tensorflow.org/install/pip)) dla Raspberry Pi z Raspbianem 9 (i Python 3) to:

```bash
sudo apt update
sudo apt install python3-dev python3-pip
sudo apt install libatlas-base-dev        # required for numpy
sudo pip3 install -U virtualenv           # system-wide install
pip3 install --user --upgrade tensorflow  # install in $HOME
``` 
I weryfikacja:
```bash
python3 -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```
*Weryfikacja* powinna na koniec dać coś w stylu:
> tf.Tensor(-596.2789, shape=(), dtype=float32)

Dla Pythona 2.7 instrukcja wygląda podobnie:
```bash
sudo apt update
sudo apt install python-dev python-pip
sudo apt install libatlas-base-dev       # required for numpy
sudo pip install -U virtualenv           # system-wide install
pip install --user --upgrade tensorflow  # install in $HOME
# Weryfikacja:
python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```

**Comment by krzysdz** [comment]
cc @Szarp

**Comment by Szarp** [comment]
Poprawione
